import { expect, test } from "@playwright/test";
import { mockWeather } from "./weather-helper";
import { defaultSurveyRules } from "../../src/lib/survey-rules";
import { surveys } from "../../src/lib/survey";
import { STORAGE_KEY, emptyProgress, goodGhosts, recordGoodConversation, completeBadConversation } from "../../src/lib/rally";
const good = () => goodGhosts.reduce((p,g) => recordGoodConversation(p,g.id), emptyProgress());
test("required questions block empty answers, failed DB retains answers and retry awards once", async ({page}) => {
 await mockWeather(page);
 await page.route("**/api/survey-rules",r => r.fulfill({json:{rules:defaultSurveyRules()}}));
 let attempts=0; const payloads:unknown[]=[];
 await page.route("**/api/survey-responses",r => {
  attempts++; payloads.push(r.request().postDataJSON());
  return r.fulfill({status:attempts===1?503:201,json:attempts===1?{error:"保存に失敗しました"}:{saved:true,ghostId:"bad-01"}});
 });
 await page.addInitScript(({key,progress}) => localStorage.setItem(key,JSON.stringify(progress)),{key:STORAGE_KEY,progress:good()});
 await page.goto("/?id=bad-01");
 const dialog=page.getByRole("dialog");
 await dialog.getByRole("button",{name:surveys["bad-01"].button}).click();
 await expect(dialog.getByRole("alert")).toBeVisible(); expect(attempts).toBe(0);
 for(const fieldset of await dialog.locator("fieldset").all())await fieldset.locator("input").first().check();
 await dialog.getByRole("button",{name:surveys["bad-01"].button}).click();
 await expect(dialog.getByRole("alert")).toContainText("保存に失敗");
 expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!).badStampIds,STORAGE_KEY)).toHaveLength(0);
 await expect(dialog.locator("fieldset input").first()).toBeDisabled();
 await dialog.getByRole("button",{name:surveys["bad-01"].button}).click();
 await expect(page.locator(".earned-dialog")).toBeVisible();
 expect(attempts).toBe(2);expect(payloads[0]).toEqual(payloads[1]);
 expect(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).badStampIds,STORAGE_KEY)).toEqual(["bad-01"]);
});
test("staff cancel preserves exchange screen, confirm hides it permanently on this device",async({page})=>{
 await mockWeather(page);
 let progress=good();
 progress=completeBadConversation(progress,"bad-01",{}).progress;
 progress=completeBadConversation(progress,"bad-02",{}).progress;
 await page.goto("/");
 await page.evaluate(({key,progress})=>localStorage.setItem(key,JSON.stringify(progress)),{key:STORAGE_KEY,progress});
 await page.reload();
 await page.getByRole("button",{name:"景品受け取り場所で プレゼントをもらう"}).click();
 page.once("dialog",dialog=>dialog.dismiss());
 await page.getByRole("button",{name:"受け取りを完了する（スタッフ用）"}).click();
 await expect(page.getByRole("button",{name:"受け取りを完了する（スタッフ用）"})).toBeVisible();
 page.once("dialog",async dialog=>{expect(dialog.message()).toContain("取り消せず");await dialog.accept();});
 await page.getByRole("button",{name:"受け取りを完了する（スタッフ用）"}).click();
 await expect(page.getByRole("heading",{name:"プレゼントは受け取り済みです"})).toBeVisible();
 await page.reload();
 await expect(page.getByRole("heading",{name:"プレゼントは受け取り済みです"})).toBeVisible();
 await expect(page.getByRole("button",{name:"景品受け取り場所で プレゼントをもらう"})).toHaveCount(0);
});
test("DB saved but device stamp write failed retains the exact submission across reload",async({page})=>{
 await mockWeather(page);
 const payloads:unknown[]=[];
 await page.route("**/api/survey-responses",r=>{payloads.push(r.request().postDataJSON());return r.fulfill({json:{saved:true,ghostId:"bad-01"}});});
 await page.addInitScript(({key,progress})=>localStorage.setItem(key,JSON.stringify(progress)),{key:STORAGE_KEY,progress:good()});
 await page.goto("/?id=bad-01");
 await page.getByRole("radio",{name:"0点",exact:true}).check();
 await page.evaluate(key=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===key)throw Error("full");return original.call(this,k,v);};},STORAGE_KEY);
 await page.getByRole("button",{name:surveys["bad-01"].button}).click();
 await expect(page.locator(".earned-dialog")).toBeVisible();
 await page.goto("/?id=bad-01");
 await expect(page.getByRole("radio",{name:"0点",exact:true})).toBeChecked();
 await page.getByRole("button",{name:surveys["bad-01"].button}).click();
 await expect(page.locator(".earned-dialog")).toBeVisible();
 expect(payloads).toHaveLength(2);expect(payloads[0]).toEqual(payloads[1]);
});
